name = "hotel-analytics-worker"
main = "index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "hotel-analytics-db"
database_id = "1b464788-6e58-4096-a50c-3fcdfeb75975"
